### PR TITLE
Bugfix/on off detection

### PR DESCRIPTION
**Pull request by ElectiveRob**
Simplify the monitor loop and ensure it keeps running.

### CODE REVIEW

**Review by PiTRiS87 — APPROVED** [review]
Checked in my fork and seems to work well

**Comment by ricardovanlaarhoven** [comment]
Is this repo still active @lucasvdh ?

**Review by lucasvdh — APPROVED** [review]

**Comment by lucasvdh** [comment]
Big thanks to @ElectiveRob making this, @PiTRiS87 for testing it and @ricardovanlaarhoven for bringing it to my attention again.

**Comment by lucasvdh** [comment]
This fix has been released as `v0.3.7`.

**Comment by PiTRiS87** [comment]
Grat Lucas... check my pull request as well... volume buttons were not working for me and I somehow fixed it... at least for my tv :))

**Pull request merged**
